import React from 'react';
import { Pressable, Text, View } from 'react-native';
import { s } from '../constants/styles';
import { money, percent, monthKey, isoToday } from '../utils/helpers';
import { Screen, Header, Metric, MiniCard, Quick, SectionTitle, TxRow, Empty } from '../components/common';
import { CategoryBars } from './ReportsScreen';

export function Dashboard({data,stats,lockedSavings,availableBalance,onAdd,onScan,onTab}){const latest=[...data.transactions].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5);const isEmpty=data.transactions.length===0&&data.budgets.length===0&&data.goals.length===0;return <Screen>
  <Header title={`Zdravo, ${data.profile.name || 'korisniče'}!`} subtitle="Pregled ličnih finansija" action="+ Unos" onAction={onAdd}/>
  {isEmpty?<View style={s.welcomeCard}><View style={s.welcomeIcon}><Text style={s.welcomeIconText}>₿</Text></View><Text style={s.welcomeTitle}>Dobrodošao u MoneyMate!</Text><Text style={s.welcomeText}>Tvoj nalog je spreman. Počni tako što ćeš evidentirati svoj prvi prihod.</Text><Pressable style={s.welcomeButton} onPress={onAdd}><Text style={s.welcomeButtonText}>＋ Dodaj prvi prihod</Text></Pressable></View>:null}
  <View style={s.hero}><Text style={s.heroLabel}>Dostupno za trošenje</Text><Text style={s.heroValue}>{money(availableBalance)}</Text><View style={s.lockedLine}><Text style={s.lockedLabel}>🔒 Zaključano za ciljeve</Text><Text style={s.lockedValue}>{money(lockedSavings)}</Text></View><View style={s.heroRow}><Metric label="Prihodi ovog meseca" value={money(stats.income)} good/><Metric label="Troškovi ovog meseca" value={money(stats.expense)}/></View></View>
  <View style={s.grid}><MiniCard label="Ukupno stanje" value={money(stats.balance)} accent={stats.balance>=0}/><MiniCard label="Mesečni saldo" value={money(stats.monthBalance)} accent={stats.monthBalance>=0}/></View><View style={s.grid}><MiniCard label="Zaključana štednja" value={money(lockedSavings)} accent/><MiniCard label="Stopa štednje" value={percent(stats.savingsRate)} accent={stats.savingsRate>=20}/></View>
  <SectionTitle title="Brze radnje"/><View style={s.quickRow}><Quick icon="＋" label="Transakcija" onPress={onAdd}/><Quick icon="◎" label="Budžeti" onPress={()=>onTab('Budžeti')}/><Quick icon="◆" label="Ciljevi" onPress={()=>onTab('Ciljevi')}/><Quick icon="▥" label="Izveštaji" onPress={()=>onTab('Izveštaji')}/></View><Pressable style={s.dashboardQrButton} onPress={onScan}><View style={s.dashboardQrIcon}><Text style={s.dashboardQrIconText}>▦</Text></View><View style={s.flex}><Text style={s.dashboardQrTitle}>Skeniraj fiskalni QR</Text><Text style={s.dashboardQrSubtitle}>Kamera čita QR sa računa i otvara automatski popunjenu transakciju.</Text></View><Text style={s.chevron}>›</Text></Pressable><Pressable style={s.recurringDashboardCard} onPress={()=>onTab('Ponavljanja')}><View style={s.recurringDashboardIcon}><Text style={s.recurringDashboardIconText}>↻</Text></View><View style={s.flex}><Text style={s.dashboardQrTitle}>Ponavljajuće transakcije</Text><Text style={s.dashboardQrSubtitle}>{(data.recurring||[]).filter(x=>x.isActive).length} aktivnih pravila · plata, kirija, pretplate i rate</Text></View><Text style={s.chevron}>›</Text></Pressable>
  <SectionTitle title="Potrošnja po kategoriji"/><CategoryBars transactions={data.transactions.filter(x=>monthKey(x.date)===monthKey(isoToday()))}/>
  <SectionTitle title="Poslednje transakcije" action="Sve" onAction={()=>onTab('Transakcije')}/><View style={s.card}>{latest.length?latest.map((x,i)=><TxRow key={x.id} item={x} last={i===latest.length-1}/>):<Empty text="Još nema transakcija. Dodaj svoj prvi prihod ili trošak."/>}</View>
</Screen>}

